-- MySQL Script generated by MySQL Workbench
-- Tue Dec 18 17:09:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `ssn` CHAR(10) NOT NULL,
  `first_name` VARCHAR(100) NULL,
  `last_name` VARCHAR(100) NULL,
  PRIMARY KEY (`ssn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Car`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Car` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Car` (
  `VIN` CHAR(16) NOT NULL,
  `model` VARCHAR(45) NULL,
  `company` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `Client_ssn` CHAR(10) NOT NULL,
  PRIMARY KEY (`VIN`),
  CONSTRAINT `fk_Car_Client`
    FOREIGN KEY (`Client_ssn`)
    REFERENCES `mydb`.`Client` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Car_Client_idx` ON `mydb`.`Car` (`Client_ssn` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`InsuranceCompany`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`InsuranceCompany` ;

CREATE TABLE IF NOT EXISTS `mydb`.`InsuranceCompany` (
  `company_name` CHAR(20) NOT NULL,
  PRIMARY KEY (`company_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Insurance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Insurance` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Insurance` (
  `insurance_id` INT NOT NULL,
  `price` DECIMAL(15,2) NULL,
  `expiration_date` DATETIME NULL,
  `payment_date` DATETIME NULL,
  `InsuranceCompany_company_name` CHAR(20) NOT NULL,
  PRIMARY KEY (`insurance_id`),
  CONSTRAINT `fk_Insurance_InsuranceCompany1`
    FOREIGN KEY (`InsuranceCompany_company_name`)
    REFERENCES `mydb`.`InsuranceCompany` (`company_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Insurance_InsuranceCompany1_idx` ON `mydb`.`Insurance` (`InsuranceCompany_company_name` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Car_has_Insurance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Car_has_Insurance` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Car_has_Insurance` (
  `Car_VIN` CHAR(16) NOT NULL,
  `Insurance_insurance_id` INT NOT NULL,
  PRIMARY KEY (`Car_VIN`, `Insurance_insurance_id`),
  CONSTRAINT `fk_Car_has_Insurance_Car1`
    FOREIGN KEY (`Car_VIN`)
    REFERENCES `mydb`.`Car` (`VIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Car_has_Insurance_Insurance1`
    FOREIGN KEY (`Insurance_insurance_id`)
    REFERENCES `mydb`.`Insurance` (`insurance_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Car_has_Insurance_Insurance1_idx` ON `mydb`.`Car_has_Insurance` (`Insurance_insurance_id` ASC);

CREATE INDEX `fk_Car_has_Insurance_Car1_idx` ON `mydb`.`Car_has_Insurance` (`Car_VIN` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Accident`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Accident` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Accident` (
  `accident_id` INT NOT NULL AUTO_INCREMENT,
  `place` VARCHAR(45) NOT NULL,
  `adate` DATETIME NOT NULL,
  `Car_VIN` CHAR(16) NOT NULL,
  PRIMARY KEY (`accident_id`),
  CONSTRAINT `fk_Accident_Car1`
    FOREIGN KEY (`Car_VIN`)
    REFERENCES `mydb`.`Car` (`VIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Accident_Car1_idx` ON `mydb`.`Accident` (`Car_VIN` ASC);

USE `mydb` ;

-- -----------------------------------------------------
-- View `mydb`.`client_car`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`client_car` ;
USE `mydb`;
CREATE  OR REPLACE VIEW `client_car` AS
SELECT ssn, VIN, first_name, last_name
FROM Client, Car
Where ssn = Client_ssn;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
